version: '3'


networks:
  net:
    name: 6uo-network
    ipam: 
      config:
        - subnet: 172.20.0.0/24


services:

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: 6uoPlatform
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    expose:
      - 3306
    networks:
      net:
        ipv4_address: 172.20.0.8
    volumes:
      - ./auth.sql:/docker-entrypoint-initdb.d/auth.sql

  uo_games_api:
    image: node:latest
    volumes:
      - ./6uoGamesAPI:/code
    working_dir: /code
    command:  npm start
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - Platform_host=db
      - ScheduleTask_host=db
      - gamePlacePlatform_host=db
    networks:
      net:
        ipv4_address: 172.20.0.5

